services:
  mariadb:
    image: mariadb:latest
    container_name: my-sqli-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sqlinjectiondb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

  web:
    image: php:apache
    container_name: my-sqli-web
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8080:80"
    volumes:
      - ./website:/var/www/html
    command: bash -c "docker-php-ext-install mysqli && apache2-foreground"

volumes:
  mariadb_data:
